"""SQLite for local use; Postgres for free hosted durable storage."""
import os,sqlite3,re
from contextlib import contextmanager
DATABASE_URL=os.environ.get('DATABASE_URL')
if DATABASE_URL:
 import psycopg
 from psycopg.rows import dict_row
 IntegrityError=psycopg.IntegrityError
else:IntegrityError=sqlite3.IntegrityError
class Row(dict):
 def __getitem__(self,key):return list(self.values())[key] if isinstance(key,int) else super().__getitem__(key)
class Result:
 def __init__(self,cursor):self.cursor=cursor
 def __iter__(self):
  for row in self.cursor:yield Row(row)
 def fetchone(self):
  row=self.cursor.fetchone();return Row(row) if row is not None else None
 def fetchall(self):return [Row(row) for row in self.cursor.fetchall()]
class Postgres:
 def __init__(self,connection):self.connection=connection
 def execute(self,sql,params=()):
  if sql=='BEGIN IMMEDIATE':
   self.connection.execute('BEGIN')
   return Result(self.connection.execute('LOCK TABLE users IN SHARE ROW EXCLUSIVE MODE'))
  sql=sql.replace('id INTEGER PRIMARY KEY,','id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,')
  if sql.startswith('INSERT OR IGNORE INTO '):
   sql=sql.replace('INSERT OR IGNORE INTO ','INSERT INTO ',1)
   returning=re.search(r'\s+RETURNING\s+',sql,re.IGNORECASE)
   if returning:sql=sql[:returning.start()]+' ON CONFLICT DO NOTHING'+sql[returning.start():]
   else:sql=sql.rstrip().rstrip(';')+' ON CONFLICT DO NOTHING'
  return Result(self.connection.execute(sql.replace('%','%%').replace('?','%s'),params))
 def executescript(self,sql):
  for statement in sql.split(';'):
   if statement.strip():self.execute(statement)
@contextmanager
def connect(path):
 if DATABASE_URL:
  with psycopg.connect(DATABASE_URL,row_factory=dict_row,connect_timeout=15) as c:yield Postgres(c)
 else:
  c=sqlite3.connect(path);c.row_factory=sqlite3.Row
  try:
   with c:yield c
  finally:c.close()
